name: Unit tests

on:
  push:
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npx vitest --coverage.enabled true
      
      - name: Report Coverage
        if: always() && github.event_name == 'pull_request'
        uses: davelosert/vitest-coverage-report-action@v2
